export const PUBLIC_LICENSE_KEY = `-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEGL33siw2E7ogD4hLkTZFPLyEIort
Eux6F1097bv8c1lSOf8gDqq/NDBBB64rxcEm7nNuBVnAQ9TwDxPNtIZo9g==
-----END PUBLIC KEY-----`;
